name: run corrections

# todo: make so that it runs on something other than push, because that sounds annoying.

on:
  push:
    branches:
      - fix-repeats-and-whitespace
      
jobs:
  fix_repeats_and_whitespace:
    name: job runs python script to fix repeats/whitespace
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
      
    - name: TODO
      run: |
        ls
        git status
        echo "new file contents" > newfile.txt
        git add newfile.txt
        
    - name: Commit files
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git commit -m "Add changes" -a
        
    - name: push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: fix-repeats-and-whitespace
